### ISSUE TITLE
.isAlive() not working in Python 3.9

### ISSUE THREAD

**Issue by bodom0015** [clowder-framework/pyclowder#25]
Attempting to install and run `pyclowder` in a base `python:3` Docker image causes failures at runtime:
```python
2021-02-18 17:24:18,705 [RabbitMQConnector] ERROR   : pyclowder.connectors - Error while consuming messages.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyclowder/connectors.py", line 713, in listen
    if self.worker.is_finished():
  File "/usr/local/lib/python3.9/site-packages/pyclowder/connectors.py", line 887, in is_finished
    return self.thread and not self.thread.isAlive() and self.finished and len(self.messages) == 0
AttributeError: 'Thread' object has no attribute 'isAlive'
```

Apparently `.isAlive()` is/was deprecated, and the name has changed to `.is_alive()` in Python 3.9

**Comment by tirkarthi** [comment]
I have created https://github.com/clowder-framework/pyclowder/pull/26 to fix this.
